version: '3.8'
services: 

  node-red:
    container_name: docker_Node-RED
    restart: unless-stopped
    build:
      context: ./node-red
      dockerfile: Dockerfile
    user: "root"
    ports:
      - "1880:1880"
    environment:
      - TZ=Europe/Amsterdam
    links:
      - influxdb

  influxdb:
    container_name: docker_InfluxDB
    restart: unless-stopped
    build:
      context: ./influxdb
      dockerfile: Dockerfile
    ports:
    - "8086:8086"
    environment:
      - DOCKER_INFLUXDB_INIT_MODE=setup
      - DOCKER_INFLUXDB_INIT_USERNAME=admin
      - DOCKER_INFLUXDB_INIT_PASSWORD=admin1234
      - DOCKER_INFLUXDB_INIT_ORG=FESB
      - DOCKER_INFLUXDB_INIT_BUCKET=TTN
    volumes:
      - "influxdb-data:/var/lib/influxdb"

  grafana:
    container_name: docker_Grafana
    restart: unless-stopped
    build:
      context: ./grafana
      dockerfile: Dockerfile
    user: "root"
    ports:
      - "3000:3000"
    volumes:
        - "grafana-data:/var/lib/grafana"
    links:
        - influxdb
    
volumes:
  influxdb-data:
  grafana-data:
